#!/bin/sh
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	printf "Usage: epoch\nPrints the current epoch time.\n"
	printf "Epoch time is the number of seconds that have elapsed since 1970-01-01 00:00:00 UTC.\n"
	exit 0
fi
exec date +"%s"
