#!/usr/bin/env python3
import sys
import fileinput
import contextlib
from typing import cast


def main() -> None:
    for line in fileinput.input(encoding="utf-8", mode="r"):
        sys.stdout.write(cast(str, line))

    sys.stdout.flush()


if __name__ == "__main__":
    with contextlib.suppress(KeyboardInterrupt):
        main()
