#!/bin/sh
havecmd -V 'This is typically installed as part of imagemagick' magick || exit $?
FILEPATH=${1:?Must provide image to convert}
exec magick convert "$FILEPATH" "$(replace-extension "$FILEPATH" png)"
